# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: BIGGAR

steps:
# Command Line v1
# Run a command line with arguments.
- task: notepad
  inputs:
    filename: # string. Required. Tool. 
    #arguments: # string. Arguments. 
  # Advanced
    #workingFolder: # string. Working folder. 
    #failOnStandardError: false # boolean. Fail on Standard Error. Default: false.