# Command Line v1
# Run a command line with arguments.

trigger:
- main

pool: Default
#  vmImage: BIGGAR

steps:
- task: CmdLine@1
  inputs:
    filename: notepad # string. Required. Tool. 
    #arguments: # string. Arguments. 
  # Advanced
    #workingFolder: # string. Working folder. 
    #failOnStandardError: false # boolean. Fail on Standard Error. Default: false.