# Command Line v1
# Run a command line with arguments.

trigger:
- main

pool: Default
#  vmImage: BIGGAR

steps:
- task: CmdLine@1
  inputs:
    filename: orqac
    arguments: BrowserTest/BrowserTest.task
    workingFolder: C:\Apps\Orqa
    failOnStandardError: true